//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewEquipas
    {
        public int IdUtilizador { get; set; }
        public string Nome { get; set; }
        public Nullable<int> TarefasDecorrer { get; set; }
        public string InspetorChefe { get; set; }
        public Nullable<int> IdInspetorChefe { get; set; }
    }
}
