//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caso()
        {
            this.Tarefa = new HashSet<Tarefa>();
        }
    
        public int IdCaso { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Objetivos { get; set; }
        public string Relatorio { get; set; }
        public int idUtilizadorResponsavel { get; set; }
        public bool Terminado { get; set; }
    
        public virtual Utilizador Utilizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarefa> Tarefa { get; set; }
    }
}
