//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesIC : DbContext
    {
        public EntitiesIC()
            : base("name=EntitiesIC")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caso> Caso { get; set; }
        public virtual DbSet<Dados> Dados { get; set; }
        public virtual DbSet<Tarefa> Tarefa { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
        public virtual DbSet<viewEquipas> viewEquipas { get; set; }
    
        public virtual ObjectResult<TarefasNaoSincronizadas_Result> TarefasNaoSincronizadas(Nullable<int> idInspetorChefe)
        {
            var idInspetorChefeParameter = idInspetorChefe.HasValue ?
                new ObjectParameter("idInspetorChefe", idInspetorChefe) :
                new ObjectParameter("idInspetorChefe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TarefasNaoSincronizadas_Result>("TarefasNaoSincronizadas", idInspetorChefeParameter);
        }
    
        public virtual ObjectResult<CasosAtivos_Result1> CasosAtivos(Nullable<int> idIC)
        {
            var idICParameter = idIC.HasValue ?
                new ObjectParameter("idIC", idIC) :
                new ObjectParameter("idIC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CasosAtivos_Result1>("CasosAtivos", idICParameter);
        }
    
        public virtual ObjectResult<TarefasIC_Result1> TarefasIC(Nullable<int> idIC)
        {
            var idICParameter = idIC.HasValue ?
                new ObjectParameter("idIC", idIC) :
                new ObjectParameter("idIC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TarefasIC_Result1>("TarefasIC", idICParameter);
        }
    
        public virtual ObjectResult<AgentesEnvolvidos_Result> AgentesEnvolvidos(Nullable<int> idCaso)
        {
            var idCasoParameter = idCaso.HasValue ?
                new ObjectParameter("idCaso", idCaso) :
                new ObjectParameter("idCaso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AgentesEnvolvidos_Result>("AgentesEnvolvidos", idCasoParameter);
        }
    
        public virtual ObjectResult<dadosRelatorioAgente_Result> dadosRelatorioAgente(Nullable<int> idAgente, Nullable<int> idCaso)
        {
            var idAgenteParameter = idAgente.HasValue ?
                new ObjectParameter("idAgente", idAgente) :
                new ObjectParameter("idAgente", typeof(int));
    
            var idCasoParameter = idCaso.HasValue ?
                new ObjectParameter("idCaso", idCaso) :
                new ObjectParameter("idCaso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dadosRelatorioAgente_Result>("dadosRelatorioAgente", idAgenteParameter, idCasoParameter);
        }
    }
}
