//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarefa()
        {
            this.Dados = new HashSet<Dados>();
        }
    
        public int IdTarefa { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Objetivos { get; set; }
        public bool Realizada { get; set; }
        public bool Exportada { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int IdAgente { get; set; }
        public int IdCaso { get; set; }
    
        public virtual Caso Caso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dados> Dados { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
