//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    
    public partial class TarefasIC_Result1
    {
        public int IdTarefa { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Objetivos { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string NomeCaso { get; set; }
        public int IdAgente { get; set; }
        public string Agente { get; set; }
        public bool Realizada { get; set; }
        public bool Exportada { get; set; }
    }
}
